"""empty message

Revision ID: 9410bec19b45
Revises: 
Create Date: 2024-06-21 13:52:19.980772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9410bec19b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('media_uri', sa.String(), nullable=True))
    op.drop_column('recipes', 'media_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('media_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'media_uri')
    # ### end Alembic commands ###
