"""empty message

Revision ID: 99a2d6e04077
Revises: 9410bec19b45
Create Date: 2024-06-21 18:21:41.985236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a2d6e04077'
down_revision: Union[str, None] = '9410bec19b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('dislikes_count', sa.Integer(), nullable=True))
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'rates_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('rates_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'dislikes_count')
    op.drop_column('recipes', 'likes_count')
    # ### end Alembic commands ###
